name: Update data
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: node scripts/update-data.js
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Arnelle Balane
          author_email: arnellebalane@gmail.com
          message: Update data (via GitHub Actions)
          add: "src/data/*"
